### PR TITLE
fix(concept:changeRequest): remove sources if egendefinert

### LINKED ISSUE #511: BUG: endringsforslag må ta høyde for "forhold til kilde" når endringer sendes inn
## 🐛 Bug rapport
Hvis bruker har valgt "egendefinert" på forhold til kilde og trykker send inn må kildene fjernes, altså at JSON-patch-operasjonen `remove` på kildene i begrepet må legges til i endringsforslaget.

### PR DESCRIPTION
**Pull request by terjesyl**
resolves #511

### CODE REVIEW

File: apps/concept-catalog/app/[catalogId]/change-requests/[changeRequestId]/edit/change-request-edit-page-client.tsx [hunk 1]
```diff
@@ -49,9 +50,13 @@ const ChangeRequestEditPageClient: FC<Props> = ({
       values.anbefaltTerm?.navn?.nn ||
       values.anbefaltTerm?.navn?.en ||
       '';
+
     const changeRequestFromConcept: ChangeRequestUpdateBody = {
       conceptId: originalConcept?.id || null,
```
Comment (pooriamehregan) [inline apps/concept-catalog/app/[catalogId]/change-requests/[changeRequestId]/edit/change-request-edit-page-client.tsx:55]:
```suggestion
      conceptId: originalConcept?.id ?? null,
```

**Review by pooriamehregan — APPROVED** [review]

**Review by pooriamehregan — APPROVED** [review]
