### PR TITLE
fix: not possible to select empty in dropdown filtert concept catalog

### LINKED ISSUE #611: [Bug]: Ikke mulig å velge "ingenting" i dropdowns begrepskatalog

### PR DESCRIPTION
**Pull request by hegeaal**
closes #611

### CODE REVIEW

File: apps/concept-catalog/components/search-filter/index.tsx [hunk 1]
```diff
@@ -125,16 +125,20 @@ const SearchFilter = ({ catalogId, internalFields, subjectCodeList, conceptStatu
...
-                      >
-                        {item.name}
-                      </option>
-                    ))
-                  : []}
+                {[
+                  <option
+                    key={'no-user-selected'}
+                    value={undefined}
+                  ></option>,
```
Comment (pooriamehregan) [inline apps/concept-catalog/components/search-filter/index.tsx:132]:
```suggestion
                  />,
```

**Review by pooriamehregan — APPROVED** [review]
