### PR TITLE
fix: custom design not showing

### LINKED ISSUE #598: [Bug]: custom design not showing in begrepskatalogen
- [ ] Custom design not showing
- [ ] Not possible to upload logo in catalog-admin

### PR DESCRIPTION
**Pull request by hegeaal**
closes #598

### CODE REVIEW

File: apps/catalog-admin/hooks/design.ts [hunk 1]
```diff
@@ -133,7 +134,7 @@ export const useDeleteLogo = (catalogId: string) => {
         method: 'DELETE',
         cache: 'no-store',
       });
-
+      console.log('Delete response', response);
```
Comment (NilsOveTen) [inline apps/catalog-admin/hooks/design.ts:137]: :x:

**Review by jeffreiffers — APPROVED** [review]
