### PR TITLE
fix: use uuid as id for codes

### LINKED ISSUE #599: [Feat]: Endre codeID til Uuid
Skatt ønsker at id'en til koder (Code) skal være stabil. Per i dag blir id'en satt i frontend som `[høyeste kode i kodelisten + 1].` Ønsker derfor å gå over til å bruke UUID istedet. 

- [x] Endringer i catalog-admin-service (back-end)
- [ ] Endringer i frontned

### PR DESCRIPTION
**Pull request by hegeaal**
closes #599

### CODE REVIEW

File: apps/catalog-admin/components/code-list-editor/index.tsx [hunk 1]
```diff
@@ -190,7 +194,7 @@ export const CodeListEditor = ({ catalogId, codeList, codeListsInUse, type, dirt
           <Button
             color='danger'
             onClick={() => {
-              handleDeleteCodeList(codeList.id);
+              handleDeleteCodeList(codeList?.id || '');
```
Comment (pooriamehregan) [inline apps/catalog-admin/components/code-list-editor/index.tsx:197]:
```suggestion
              handleDeleteCodeList(codeList?.id ?? '');
```

File: apps/catalog-admin/components/codes-editor/index.tsx [hunk 2]
```diff
@@ -16,52 +16,37 @@ import {
...
 
 export const CodesEditor = ({ codeList: dbCodeList, dirty }: Props) => {
   const adminDispatch = useAdminDispatch();
   const { updatedCodeLists, updatedCodes } = useAdminState();
 
-  const codeListInContext = updatedCodeLists?.find((codeList) => codeList.id === dbCodeList.id);
+  const codeListInContext = updatedCodeLists?.find((codeList) => codeList.id === dbCodeList?.id);
   const currentCodeList = codeListInContext ?? dbCodeList;
-  const codes = updatedCodes ? updatedCodes[dbCodeList?.id] || updatedCodes['0'] : [];
+  const codes = updatedCodes ? updatedCodes[dbCodeList?.id || ''] || updatedCodes['0'] : [];
```
Comment (pooriamehregan) [inline apps/catalog-admin/components/codes-editor/index.tsx:36]:
```suggestion
  const codes = updatedCodes ? updatedCodes[dbCodeList?.id ?? ''] || updatedCodes['0'] : [];
```

File: apps/catalog-admin/components/codes-editor/index.tsx [hunk 3]
```diff
@@ -16,52 +16,37 @@ import {
...
 
   const [selectedCode, setSelectedCode] = useState<Code>();
   const [isEditViewOpen, setIsEditViewOpen] = useState<boolean>(false);
 
   const setDirtyState = () => {
     if (dirty) {
       const isDirty =
-        compare(dbCodeList?.codes ?? [], updatedCodes[dbCodeList?.id] ?? []).length > 0 ||
-        (selectedCode && !dbCodeList?.codes?.includes(selectedCode));
+        compare(dbCodeList?.codes ?? [], updatedCodes?.[dbCodeList?.id || ''] ?? []).length > 0 ||
```
Comment (pooriamehregan) [inline apps/catalog-admin/components/codes-editor/index.tsx:44]:
```suggestion
        compare(dbCodeList?.codes ?? [], updatedCodes?.[dbCodeList?.id ?? ''] ?? []).length > 0 ||
```

File: apps/catalog-admin/components/codes-editor/index.tsx [hunk 4]
```diff
@@ -212,8 +196,8 @@ export const CodesEditor = ({ codeList: dbCodeList, dirty }: Props) => {
     return [...relatedCodes, ...descendants];
   }
 
-  function availableParentCodes(codes: Code[], codeId: number) {
-    const relatedCodes = findRelatedCodes(codes, codeId) || [];
+  function availableParentCodes(codes: Code[], codeId: string | undefined) {
+    const relatedCodes = findRelatedCodes(codes, codeId || '') || [];
```
Comment (pooriamehregan) [inline apps/catalog-admin/components/codes-editor/index.tsx:200]:
```suggestion
    const relatedCodes = findRelatedCodes(codes, codeId ?? '') || [];
```

**Review by pooriamehregan — APPROVED** [review]
