### PR TITLE
fix: show concept status label in filter chips

### LINKED ISSUE #306: Bug: Label for begrepsstatus vises ikke på valgt filter.

### PR DESCRIPTION
**Pull request by NilsOveTen**
resolve #306

### CODE REVIEW

File: apps/concept-catalog/pages/[catalogId]/index.tsx [hunk 1]
```diff
@@ -11,6 +11,7 @@ import {
 } from '@catalog-frontend/ui';
 import {
   capitalizeFirstLetter,
+  getTranslateText as translate,
```
Comment (jeffreiffers) [inline apps/concept-catalog/pages/[catalogId]/index.tsx:14]: Du har allerede importert getTranslatedText

**Review by jeffreiffers — CHANGES_REQUESTED** [review]

File: apps/concept-catalog/pages/[catalogId]/index.tsx (hunk 1 above)
Comment (NilsOveTen) [reply apps/concept-catalog/pages/[catalogId]/index.tsx]: c2c42fa

**Review by jeffreiffers — APPROVED** [review]
