### PR TITLE
fix: replace fulltext (deprecated) with new search service

### LINKED ISSUE #648: [Bug]: Concept catalog - erstatt full text-search (getRelatedConcepts) med search-service
### Nåværende oppførsel
Concept catalog bruker fremdeles fulltext-search til getReleatedConcepts. Denne skal erstattes med search-service.

Lenke til relatert begrep:
Hvis man er i registreringsløsningen så kan man jo ha relatert til interne begrep som er publiser/ikke publisert, samt til publiserte begrep til andre. Er det egne begrep man har relatert til (publisert/ikke publisert) så forventer kanskje brukeren å komme til det relaterte begrepet i reg.løsningen, mens for begreper som tilhører andre må man komme til detaljesiden i portalen/data.norge.
Er man i portalen data.norge så forventes det at lenken går til detaljesiden til begrepet på data.norge.
Og så har man ev. de tilfellene det gjennom høsting er relatert til begrep som ikke finnes på data.norge og da brukes URI-en som er lagt til i filen som høstes. Hvis term og definisjon er lagt til i filen som høstes så vises dette i de tilfeller dette skal vises. (edited)

### PR DESCRIPTION
**Pull request by jeffreiffers**
Fixes #648

### CODE REVIEW

File: libs/data-access/src/lib/concept/api/index.ts [hunk 1]
```diff
@@ -120,11 +126,24 @@ export const getRelatedConcepts = async (concept: Concept): Promise<SkosConcept[
     relatedConceptsUris.push(...concept.erstattesAv);
   }
 
+  console.log('uris', relatedConceptsUris);
```
Comment (hegeaal) [inline libs/data-access/src/lib/concept/api/index.ts:129]:
```suggestion
```

**Review by hegeaal — APPROVED** [review]
